import { CategoryInfo, MenuItem, MatchBroadcast, CafeSchedule } from '@/types/menu';

export const CAFE_METADATA = {
  name: 'ZenZoo Café',
  nameAr: 'مقهى زين زو',
  taglineFr: 'Café traditionnel & Terrasse au cœur de Safi',
  taglineAr: 'المقهى التقليدي وإطلالة ساحرة بقلب مدينة آسفي',
  city: 'Safi',
  cityAr: 'آسفي',
  address: 'Boulevard Hassan II, Centre-Ville, Safi 46000',
  addressShort: 'Bd Hassan II · Centre-Ville Safi',
  plusCode: '7QRF+2C4 Safi',
  mapsUrl: process.env.NEXT_PUBLIC_MAPS_LOCATION_URL || 'https://maps.google.com/?q=7QRF%2B2C4+Safi',
  phone: process.env.NEXT_PUBLIC_PHONE_NUMBER || '+212524620000',
  phoneDisplay: '05 24 62 00 00',
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '212600000000',
  whatsappDisplay: '+212 600-000000',
  openingTime: '05:00',
  closingTime: '01:00',
  currency: 'MAD',
  currencyAr: 'د.م',
  timezone: 'Africa/Casablanca',
};

export const MENU_CATEGORIES: CategoryInfo[] = [
  {
    id: 'cafe-chaud',
    labelFr: 'Cafés Chauds',
    labelAr: 'قهوة ساخنة',
    subtitleFr: 'Torréfaction intense & grains sélectionnés',
    iconName: 'Coffee',
  },
  {
    id: 'the-infusions',
    labelFr: 'Thés & Infusions',
    labelAr: 'شاي وأعشاب',
    subtitleFr: 'Menthe fraîche berguia, chiba & verveine',
    iconName: 'Flame',
  },
  {
    id: 'boissons-fraiches',
    labelFr: 'Boissons Fraîches',
    labelAr: 'مشروبات باردة',
    subtitleFr: 'Eaux minérales & sodas bien frais',
    iconName: 'Sparkles',
  },
  {
    id: 'jus-naturels',
    labelFr: 'Jus Naturels',
    labelAr: 'عصائر طبيعية',
    subtitleFr: 'Fruits pressés minute à la commande',
    iconName: 'Citrus',
  },
  {
    id: 'petit-dejeuner',
    labelFr: 'Petit-Déjeuner',
    labelAr: 'فطور الصباح',
    subtitleFr: 'Formules complètes & spécialités beldi',
    iconName: 'Sunrise',
  },
  {
    id: 'snacks-patisserie',
    labelFr: 'Pâtisserie & Beldi',
    labelAr: 'حلويات وفطائر',
    subtitleFr: 'Viennoiseries croustillantes & galettes chaudes',
    iconName: 'Croissant',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // 1. Cafés Chauds
  {
    id: 'cafe-noir',
    nameFr: 'Café Noir / Espresso',
    nameAr: 'قهوة كحلة / إكسبريسو',
    descriptionFr: 'Espresso italien intense servi avec petit verre d’eau fraîche',
    priceMAD: 10,
    category: 'cafe-chaud',
    isPopular: true,
    tags: ['signature'],
  },
  {
    id: 'cafe-casse',
    nameFr: 'Café Cassé (Noss-Noss)',
    nameAr: 'قهوة مهرسة (نص نص)',
    descriptionFr: 'Le classique marocain : moitié espresso, moitié lait chaud émulsionné',
    priceMAD: 12,
    category: 'cafe-chaud',
    isPopular: true,
    tags: ['signature', 'morning'],
  },
  {
    id: 'cafe-creme-grand',
    nameFr: 'Café au Lait Grand Verre',
    nameAr: 'قهوة بالحليب كوب كبير',
    descriptionFr: 'Servi traditionnellement dans un grand verre avec mousse onctueuse',
    priceMAD: 13,
    category: 'cafe-chaud',
    tags: ['morning'],
  },
  {
    id: 'cafe-serre',
    nameFr: 'Café Serré (Ristretto)',
    nameAr: 'قهوة مركّزة (ريستريتو)',
    descriptionFr: 'Extraction courte, corps dense et crema dorée',
    priceMAD: 10,
    category: 'cafe-chaud',
  },
  {
    id: 'cafe-americain',
    nameFr: 'Café Allongé / Américain',
    nameAr: 'قهوة مخففة (أمريكانو)',
    descriptionFr: 'Espresso étiré à l’eau chaude, saveur douce et prolongée',
    priceMAD: 11,
    category: 'cafe-chaud',
  },
  {
    id: 'cappuccino-maison',
    nameFr: 'Cappuccino Mousse de Lait',
    nameAr: 'كابوتشينو برغوة الحليب',
    descriptionFr: 'Double shot de café, micro-mousse de lait et soupçon de cacao amer',
    priceMAD: 15,
    category: 'cafe-chaud',
  },

  // 2. Thés & Infusions
  {
    id: 'the-menthe',
    nameFr: 'Thé à la Menthe Traditionnel',
    nameAr: 'أتاي بالنعناع البركَي',
    descriptionFr: 'Thé vert gunpowder infusé à la menthe berguia fraîche, servi au berrad',
    priceMAD: 11,
    category: 'the-infusions',
    isPopular: true,
    tags: ['signature'],
  },
  {
    id: 'the-chiba',
    nameFr: 'Thé à la Chiba (Absinthe)',
    nameAr: 'أتاي بالشيبة الأصيلة',
    descriptionFr: 'Feuilles d’absinthe sauvage fraîche, arôme hivernal corsé et réconfortant',
    priceMAD: 12,
    category: 'the-infusions',
  },
  {
    id: 'the-louiza',
    nameFr: 'Infusion Louiza (Verveine pure)',
    nameAr: 'شاي اللويزة البلدية',
    descriptionFr: 'Feuilles de verveine séchée du terroir, vertus digestives et apaisantes',
    priceMAD: 12,
    category: 'the-infusions',
  },
  {
    id: 'the-noir-citron',
    nameFr: 'Thé Noir Chaud au Citron',
    nameAr: 'شاي أسود مع ليمون حامض',
    descriptionFr: 'Sélection de thé noir de Ceylan avec tranche de citron frais de Safi',
    priceMAD: 11,
    category: 'the-infusions',
  },

  // 3. Boissons Fraîches
  {
    id: 'eau-sidi-ali',
    nameFr: 'Eau Minérale Sidi Ali 50cl',
    nameAr: 'ماء معدني سيدي علي 50 سل',
    descriptionFr: 'Bouteille individuelle fraîche capsulée',
    priceMAD: 6,
    category: 'boissons-fraiches',
    tags: ['cold'],
  },
  {
    id: 'eau-oulmes',
    nameFr: 'Eau Minérale Gazeuse Oulmès 50cl',
    nameAr: 'ماء غازي طبيعي والماس 50 سل',
    descriptionFr: 'Eau gazeuse naturelle marocaine avec quartier de citron',
    priceMAD: 8,
    category: 'boissons-fraiches',
    tags: ['cold'],
  },
  {
    id: 'soda-canette',
    nameFr: 'Soda Canette Fraîche 33cl',
    nameAr: 'مشروب غازي مثلج 33 سل',
    descriptionFr: 'Coca-Cola, Hawaii Tropical, Poms Pomme, Schweppes Tonic ou Citron',
    priceMAD: 10,
    category: 'boissons-fraiches',
    tags: ['cold'],
  },
  {
    id: 'red-bull',
    nameFr: 'Boisson Énergisante 25cl',
    nameAr: 'مشروب طاقة منشط 25 سل',
    descriptionFr: 'Servie glacée pour les soirées de match',
    priceMAD: 25,
    category: 'boissons-fraiches',
    tags: ['cold'],
  },

  // 4. Jus Naturels
  {
    id: 'jus-orange',
    nameFr: 'Jus d’Orange Pressé Minute',
    nameAr: 'عصير برتقال طبيعي معصور',
    descriptionFr: '100% oranges marocaines gorgées de soleil, pressées à la commande',
    priceMAD: 16,
    category: 'jus-naturels',
    isPopular: true,
    tags: ['signature', 'morning', 'cold'],
  },
  {
    id: 'panache-maison',
    nameFr: 'Panaché Fruits ZenZoo',
    nameAr: 'بناشي فواكه مشكلة خاص بالمقهى',
    descriptionFr: 'Avocat crémeux, banane, pomme, lait frais, amandes et filet de miel',
    priceMAD: 22,
    category: 'jus-naturels',
    isPopular: true,
    tags: ['signature', 'cold'],
  },
  {
    id: 'jus-avocat-lait',
    nameFr: 'Jus d’Avocat au Lait & Fruits Secs',
    nameAr: 'عصير أفوكا بالحليب وفواكه جافة',
    descriptionFr: 'Avocat entier mixé au lait entier, garni d’amandes et de noix concassées',
    priceMAD: 25,
    category: 'jus-naturels',
    tags: ['cold'],
  },
  {
    id: 'jus-citron-gingembre',
    nameFr: 'Jus de Citron & Menthe Fraîche',
    nameAr: 'عصير ليمون حامض مع نعناع طازج',
    descriptionFr: 'Citrons pressés, pointe de gingembre, feuilles de menthe et glace pilée',
    priceMAD: 15,
    category: 'jus-naturels',
    tags: ['cold'],
  },

  // 5. Petit-Déjeuner
  {
    id: 'formule-ftour-beldi',
    nameFr: 'Formule Ftour Beldi Complet',
    nameAr: 'فطور بلدي تقليدي متكامل',
    descriptionFr: '2 œufs au plat à l’huile d’olive vierge, fromage jben, olives noires de Safi, miel pur, corbeille de pain chaud & boisson chaude',
    priceMAD: 28,
    category: 'petit-dejeuner',
    isPopular: true,
    tags: ['signature', 'morning'],
  },
  {
    id: 'formule-express',
    nameFr: 'Formule Express du Matin',
    nameAr: 'فطور الصباح السريع',
    descriptionFr: 'Un café au choix ou thé berrad + 1 viennoiserie au beurre + 1 verre d’eau minérale',
    priceMAD: 16,
    category: 'petit-dejeuner',
    tags: ['morning'],
  },
  {
    id: 'omelette-khlii',
    nameFr: 'Omelette au Khlii Traditionnel',
    nameAr: 'أومليت بالخليع الفاسي الأصيل',
    descriptionFr: '3 œufs frais battus cuits avec viande séchée confite dans la poêle en fonte',
    priceMAD: 26,
    category: 'petit-dejeuner',
    isPopular: true,
    tags: ['morning'],
  },
  {
    id: 'toast-fromage-huile',
    nameFr: 'Tartines Toastées & Huile d’Olive',
    nameAr: 'طوسط محمص بزيت الزيتون والجبن',
    descriptionFr: 'Pain de campagne grillé, huile d’olive pressée de Safi, fromage blanc et thym',
    priceMAD: 18,
    category: 'petit-dejeuner',
    tags: ['morning'],
  },

  // 6. Pâtisserie & Snacks
  {
    id: 'croissant-beurre',
    nameFr: 'Croissant Pur Beurre',
    nameAr: 'كرواسون مقرمش بالزبدة',
    descriptionFr: 'Viennoiserie artisanale dorée et feuilletée, livrée chaque matin',
    priceMAD: 6,
    category: 'snacks-patisserie',
    tags: ['morning'],
  },
  {
    id: 'pain-chocolat',
    nameFr: 'Pain au Chocolat Feuilleté',
    nameAr: 'بتي بان بالشوكولاتة',
    descriptionFr: 'Double barre de chocolat noir fondant et pâte pur beurre',
    priceMAD: 7,
    category: 'snacks-patisserie',
    tags: ['morning'],
  },
  {
    id: 'msemmen-miel',
    nameFr: 'Msemmen Chaud au Miel & Beurre',
    nameAr: 'مسمن مورق ساخن بالعسل والزبدة',
    descriptionFr: 'Galette feuilletée traditionnelle servie tiède avec beurre fondu et miel',
    priceMAD: 8,
    category: 'snacks-patisserie',
    isPopular: true,
    tags: ['signature', 'morning'],
  },
  {
    id: 'harcha-beldi',
    nameFr: 'Harcha Traditionnelle au Beurre Beldi',
    nameAr: 'حرشة بالسميد والزبدة البلدية',
    descriptionFr: 'Galette de semoule fine dorée à la poêle, texture fondante',
    priceMAD: 7,
    category: 'snacks-patisserie',
    tags: ['morning'],
  },
  {
    id: 'baghrir-miel',
    nameFr: 'Baghrir aux Mille Trous',
    nameAr: 'بغرير خفيف بالعسل والزبدة',
    descriptionFr: 'Crêpe alvéolée berbère imbibée de beurre doux et miel de fleurs',
    priceMAD: 8,
    category: 'snacks-patisserie',
  },
];

export const CAFE_SCHEDULES: CafeSchedule[] = [
  { dayOfWeek: 0, openTime: '05:00', closeTime: '01:00' }, // Dimanche
  { dayOfWeek: 1, openTime: '05:00', closeTime: '01:00' }, // Lundi
  { dayOfWeek: 2, openTime: '05:00', closeTime: '01:00' }, // Mardi
  { dayOfWeek: 3, openTime: '05:00', closeTime: '01:00' }, // Mercredi
  { dayOfWeek: 4, openTime: '05:00', closeTime: '01:00' }, // Jeudi
  { dayOfWeek: 5, openTime: '05:00', closeTime: '01:00' }, // Vendredi
  { dayOfWeek: 6, openTime: '05:00', closeTime: '01:00' }, // Samedi
];

export const FEATURED_MATCH: MatchBroadcast = {
  id: 'match-ocs-botola',
  tournament: 'Botola Pro Inwi · 24ème Journée',
  teams: ['Olympique Club de Safi (OCS)', 'Raja Club Athletic'],
  kickoffTime: '20:00',
  date: 'Ce soir en direct',
  isToday: true,
  channel: 'Arryadia HD & BeIN Sports',
  venueComment: 'Retransmission en direct sur écran géant en terrasse et salle climatisée',
};

export const OPERATIONAL_AMENITIES = [
  {
    id: 'cash-only',
    titleFr: 'Paiement en Espèces Uniquement',
    titleAr: 'الأداء نقداً فقط (كاش)',
    descriptionFr: 'Règlement direct auprès du serveur ou au comptoir (MAD). Monnaie disponible.',
    iconName: 'Banknote',
  },
  {
    id: 'hours',
    titleFr: 'Service Continu 05:00 — 01:00',
    titleAr: 'مفتوح يومياً من 05:00 إلى 01:00',
    descriptionFr: 'Ouvert 7 jours sur 7. Premier espresso à 5h du matin pour les lève-tôt.',
    iconName: 'Clock',
  },
  {
    id: 'terrace',
    titleFr: 'Terrace Ombragée & Salle Intérieure',
    titleAr: 'جلسة خارجية مشمسة وصالون مكيف',
    descriptionFr: 'Plus de 40 tables extérieures avec brumisateurs l’après-midi.',
    iconName: 'Sun',
  },
  {
    id: 'live-tv',
    titleFr: 'Écrans TV & Matchs en Direct',
    titleAr: 'شاشات عملاقة لمتابعة المباريات',
    descriptionFr: 'Retransmission de tous les matchs de l’OCS, Botola Pro et Ligue des Champions.',
    iconName: 'Tv',
  },
  {
    id: 'wifi',
    titleFr: 'Wi-Fi Fibre Optique Gratuit',
    titleAr: 'إنترنت واي فاي فائق السرعة مجاناً',
    descriptionFr: 'Connexion rapide disponible pour tous les clients du café.',
    iconName: 'Wifi',
  },
];
